Upgrade Nginx to 1.25.0
theplant/ip2location-nginx pull request #25
Opened 2023-09-04 02:51 UTC by hcsu

https://theplanttokyo.atlassian.net/browse/SEC-2388

2023-09-18 04:15 UTC, geckofu requested changes

2023-09-18 04:15 UTC, geckofu commented on nginx.conf
> +    # ip2location_access_type cache_memory;
@hcsu please delete these lines if these are legacy configurations

2023-09-19 00:58 UTC, hcsu commented on nginx.conf
> +    # ip2location_access_type cache_memory;
Yes, according to this issue, these configurations are not needed

https://github.com/ip2location/ip2location-nginx/issues/12

2023-09-21 07:14 UTC, geckofu approved these changes

2023-09-24 12:04 UTC, merged